name: Deploy Backend to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy backend
        run: |
          set -e
          cd /home/ubuntu/programming/Raykulam_Backend

          git fetch origin
          git reset --hard origin/master

          npm install --production

          pm2 restart backend
          pm2 save
